"""Helpers for attaching structured layout slots to signatures.

Examples
--------
>>> from docutils import nodes
>>> from sphinx import addnodes
>>> sig = addnodes.desc_signature()
>>> source = nodes.inline(classes=["viewcode-link"])
>>> source += nodes.Text("[source]")
>>> sig += nodes.reference("", "", source, internal=False)
>>> badge = nodes.inline("", "function")
>>> inject_signature_slots(
...     sig,
...     marker_attr="demo_slots",
...     badge_node=badge,
... )
True
>>> [child.get("slot") for child in sig.children if child.get("slot")]
['badges', 'source-link']
"""

from __future__ import annotations

from docutils import nodes
from sphinx import addnodes

from sphinx_ux_autodoc_layout._nodes import build_api_slot


def is_viewcode_ref(node: nodes.Node) -> bool:
    """Return ``True`` when *node* is a viewcode/source reference.

    Parameters
    ----------
    node : nodes.Node
        Candidate node from a signature row.

    Returns
    -------
    bool
        ``True`` when the node is a source-link reference generated by
        Sphinx's viewcode integration.
    """
    return isinstance(node, nodes.reference) and any(
        "viewcode-link" in getattr(child, "get", lambda *_: [])("classes", [])
        for child in node.children
        if isinstance(child, nodes.inline)
    )


def inject_signature_slots(
    sig_node: addnodes.desc_signature,
    *,
    marker_attr: str,
    badge_node: nodes.Node | None = None,
    source_node: nodes.reference | None = None,
    extract_source_link: bool = True,
) -> bool:
    """Attach shared badge/source slots to ``sig_node`` once.

    Parameters
    ----------
    sig_node : addnodes.desc_signature
        Signature node to update.
    marker_attr : str
        Idempotence flag stored on the signature node.
    badge_node : nodes.Node | None
        Badge-group node to attach to ``api_slot("badges")``.
    source_node : nodes.reference | None
        Explicit source link to attach to ``api_slot("source-link")``.
        When omitted, the helper can promote an existing viewcode reference.
    extract_source_link : bool
        When ``True``, remove the first existing viewcode/source reference from
        ``sig_node`` and move it into the ``source-link`` slot.

    Returns
    -------
    bool
        ``True`` when the signature was updated and ``False`` when
        ``marker_attr`` was already set.
    """
    if sig_node.get(marker_attr):
        return False
    sig_node[marker_attr] = True

    extracted_source = source_node
    if extract_source_link:
        for child in list(sig_node.children):
            if not is_viewcode_ref(child):
                continue
            sig_node.remove(child)
            if extracted_source is None:
                assert isinstance(child, nodes.reference)
                extracted_source = child
            break

    if badge_node is not None:
        sig_node += build_api_slot("badges", badge_node)
    if extracted_source is not None:
        sig_node += build_api_slot("source-link", extracted_source)
    return True
