"""Generated ``src/content.config.ts`` rendering.

The Astro side wires its content collections through a TypeScript file
that imports Zod schemas from ``@gp-sphinx-astro/theme`` and registers
them with ``defineCollection``. Pydantic owns the canonical data shapes,
so it makes sense to also own the collection wiring — the TypeScript
file is generated by the builder during ``finish()`` rather than
hand-maintained, which keeps the schema registration in lockstep with
the emitted artefacts (`src/content/docs/**/*.json`,
`src/content/api/symbols.json`, `xref-index.json`).
"""

from __future__ import annotations

_TEMPLATE = """\
// AUTO-GENERATED by gp-sphinx-astro-builder. Do not edit by hand;
// regenerate by running `sphinx-build -b astro <src> <out>`.

import { defineCollection } from 'astro:content'
import { file, glob } from 'astro/loaders'
import { documentSchema } from '@gp-sphinx-astro/theme/schemas/doctree'
import { symbolSchema } from '@gp-sphinx-astro/theme/schemas/symbol'
import { xrefEntrySchema } from '@gp-sphinx-astro/theme/schemas/xref'

export const collections = {
  docs: defineCollection({
    loader: glob({ pattern: '**/*.json', base: './src/content/docs' }),
    schema: documentSchema,
  }),
  api: defineCollection({
    loader: file('src/content/api/symbols.json'),
    schema: symbolSchema,
  }),
  xrefs: defineCollection({
    loader: file('xref-index.json'),
    schema: xrefEntrySchema,
  }),
}
"""


def render_content_config() -> str:
    """Return the canonical ``content.config.ts`` source.

    The function is intentionally parameter-less for now — every consumer
    of the builder needs the same three collections (``docs``, ``api``,
    ``xrefs``), each pointed at the canonical artefact paths the builder
    emits. Parametrise when a real consumer needs to disable or rename
    one of the three.

    Returns
    -------
    str
        TypeScript source as a single string, newline-terminated.

    Examples
    --------
    >>> from gp_sphinx_astro_builder.content_config import render_content_config
    >>> source = render_content_config()
    >>> "documentSchema" in source
    True
    """
    return _TEMPLATE
