[theme]
inherit = furo
stylesheet = styles/furo.css, css/custom.css, css/argparse-highlight.css
pygments_style = a11y-light
sidebars =
  sidebar/scroll-start.html,
  sidebar/brand.html,
  sidebar/search.html,
  sidebar/navigation.html,
  sidebar/projects.html,
  sidebar/scroll-end.html

[options]
announcement =
dark_css_variables =
dark_logo =
light_css_variables =
light_logo =
sidebar_hide_name =
footer_icons =
top_of_page_button = edit
top_of_page_buttons =
source_repository =
source_branch =
source_directory =
source_edit_link =
source_view_link =
mask_icon =
show_meta_manifest_tag =
show_meta_og_tags =
show_meta_app_icon_tags =
project_name =
project_title =
project_description =
project_url =
