import { z } from "zod";

/**
 * Furo's public CSS custom-property contract.
 *
 * Sourced from upstream Furo's SCSS at the pinned commit; see
 * `upstream/furo-vars.json` for provenance and `pnpm harvest` for
 * regeneration. Consumers depend on this set as a literal-union type so
 * downstream Tailwind plugins and theme configs get exhaustive checks.
 */
export const FURO_TOKEN_NAMES = [
  "--color-admonition-background",
  "--color-announcement-background",
  "--color-announcement-text",
  "--color-api-added",
  "--color-api-added-border",
  "--color-api-background",
  "--color-api-background-hover",
  "--color-api-changed",
  "--color-api-changed-border",
  "--color-api-deprecated",
  "--color-api-deprecated-border",
  "--color-api-keyword",
  "--color-api-name",
  "--color-api-overall",
  "--color-api-paren",
  "--color-api-pre-name",
  "--color-api-removed",
  "--color-api-removed-border",
  "--color-background-border",
  "--color-background-hover",
  "--color-background-hover--transparent",
  "--color-background-item",
  "--color-background-muted",
  "--color-background-primary",
  "--color-background-secondary",
  "--color-brand-content",
  "--color-brand-primary",
  "--color-brand-visited",
  "--color-card-background",
  "--color-card-border",
  "--color-card-marginals-background",
  "--color-content-background",
  "--color-content-foreground",
  "--color-foreground-border",
  "--color-foreground-muted",
  "--color-foreground-primary",
  "--color-foreground-secondary",
  "--color-guilabel-background",
  "--color-guilabel-border",
  "--color-guilabel-text",
  "--color-header-background",
  "--color-header-border",
  "--color-header-text",
  "--color-highlight-on-target",
  "--color-highlighted-background",
  "--color-highlighted-text",
  "--color-inline-code-background",
  "--color-link",
  "--color-link--hover",
  "--color-link--visited",
  "--color-link--visited--hover",
  "--color-link-underline",
  "--color-link-underline--hover",
  "--color-link-underline--visited",
  "--color-link-underline--visited--hover",
  "--color-problematic",
  "--color-sidebar-background",
  "--color-sidebar-background-border",
  "--color-sidebar-brand-text",
  "--color-sidebar-caption-text",
  "--color-sidebar-item-background",
  "--color-sidebar-item-background--current",
  "--color-sidebar-item-background--hover",
  "--color-sidebar-item-expander-background",
  "--color-sidebar-item-expander-background--hover",
  "--color-sidebar-link-text",
  "--color-sidebar-link-text--top-level",
  "--color-sidebar-search-background",
  "--color-sidebar-search-background--focus",
  "--color-sidebar-search-border",
  "--color-sidebar-search-icon",
  "--color-sidebar-search-text",
  "--color-table-border",
  "--color-table-header-background",
  "--color-toc-background",
  "--color-toc-item-text",
  "--color-toc-item-text--active",
  "--color-toc-item-text--hover",
  "--color-toc-title-text",
  "--header-height",
  "--header-padding",
  "--sidebar-caption-space-above",
  "--sidebar-expander-width",
  "--sidebar-item-height",
  "--sidebar-item-line-height",
  "--sidebar-item-spacing-horizontal",
  "--sidebar-item-spacing-vertical",
  "--sidebar-search-icon-size",
  "--sidebar-search-input-height",
  "--sidebar-search-input-spacing-horizontal",
  "--sidebar-search-input-spacing-vertical",
  "--sidebar-search-space-above",
  "--sidebar-tree-space-above",
  "--toc-font-size--mobile",
  "--toc-item-spacing-horizontal",
  "--toc-item-spacing-vertical",
  "--toc-spacing-horizontal",
  "--toc-spacing-vertical",
  "--toc-title-padding",
] as const;

export type FuroTokenName = (typeof FURO_TOKEN_NAMES)[number];

export const FuroTokenNameSchema = z.enum(FURO_TOKEN_NAMES);
